gofacts_project/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from store import views

handler404 = 'store.views.page_not_found_view'
handler500 = 'store.views.server_error_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls', namespace='store')),
    path('store/', include('django.contrib.auth.urls')),
    path('', views.index, name='index')
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

store/urls.py
# store/urls.py
from django.urls import path
from django.views.generic import TemplateView
from store import views

app_name = 'store'
handler404 = 'views.page_not_found_view'
handler500 = 'views.server_error_view'

# https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/

urlpatterns = [
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),

    path('404/', views.page_not_found_view),
    path('500/', views.server_error_view),

    path('search/', views.search, name='search'),

    path('signup/', views.SignUp.as_view(),
         name='signup'),

    path('profile/', views.profile_page,
         name='profile_page'),

    path('update_profile/', views.update_profile,
         name='update_profile'),

    path('search/<int:product_code>', views.search,
         name='search'),

    path('product_page/<int:product_code>', views.product_page,
         name='product_page'),

    path('products/', views.products_page,
         name='products'),

    path('save/prod=<int:product_code>&sub=<int:substitute_code>', views.save_products_pair,
         name='save'),

    path('delete/product_id=<int:product_id>&substitute_id=<int:substitute_id>', views.delete_products_pair,
         name='delete'),

    path('legal/', TemplateView.as_view(template_name='store/legal.html'),
         name='legal'),

]

store/models.py
"""Models used for the application"""
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    types = (
        (0, 'Girl'),
        (1, 'Boy'),
        (2, 'Other')
    )
    user = models.ForeignKey(User, default='', on_delete=models.CASCADE)
    gender = models.SmallIntegerField(choices=types, default='0', db_index=True)


class Product(models.Model):
    """Model use to stock products"""
    name = models.CharField(max_length=200)
    image = models.URLField()
    categories = models.TextField(max_length=1500)
    grade = models.CharField(max_length=5)
    nutriments = models.TextField(max_length=1500)
    code = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.name, self.grade}"


class Favorite(models.Model):
    """Model used to stock the favorites products of an user"""
    User = get_user_model()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default='', related_name='product')
    substitute = models.ForeignKey(Product, on_delete=models.CASCADE, default='', related_name='substitute')

    def __str__(self):
        return self.user

store/views.py
"""
This file handle django app views (store/views.py)
"""
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.http import Http404
from django.shortcuts import render_to_response, render
from django.template import RequestContext
from django.urls import reverse_lazy
from django.views import generic

from gofacts_project import settings
from store import logic
from .models import Product, Profile


def page_not_found_view(request, exception=None):
    """
    Page not found
    :param request:
    :param exception:
    :return: Page not found page
    """
    context = RequestContext(request)
    err_code = 404
    response = render_to_response('store/404.html', {"code": err_code}, context)
    response.status_code = 404
    return response


def server_error_view(request, exception=None):
    """
    Server error
    :param request:
    :param exception:
    :return: Server error page
    """
    context = RequestContext(request)
    err_code = 500
    response = render_to_response('store/500.html', {"code": err_code}, context)
    response.status_code = 500
    return response


class SignUp(generic.CreateView):
    """
    Sign up
    """
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'store/signup.html'


def index(request):
    """
    Index page
    :param request:
    :return: Index page
    """
    # .order_by('-created_at')[:12]
    # products = Product.objects.filter(available=True)
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'store/index.html', context)


def search(request, product_code=None):
    """
    Search product and substitutes
    :param request:
    :param product_code:
    :return: results page
    """
    query = request.GET.get('query')
    full_result = request.GET.get('full_result')
    product_array = logic.get_product_array(query, product_code)

    if product_code is not None:
        full_result = True

    if product_array is not None:
        print("Product is found in view ! (view)")

        [
            product_name,
            product_code,
            product_grade,
            product_image,
            product_categories,
            product_nutriments
        ] \
            = product_array

        substitutes = None
        if full_result:
            print("Now for the substitutes ! (view)")
            substitutes = logic.get_substitutes(product_categories, product_array[1], product_grade)

        product_code = logic.int_code(product_code)
        context = {
            'query': query,
            'categories': product_categories,
            'product_name': product_name,
            'product_code': product_code,
            'product_grade': product_grade,
            'product_image': product_image,
            'product_nutriments': product_nutriments,
            'full_result': full_result,
            'substitutes': substitutes
        }
        return render(request, 'store/results.html', context)

    raise Http404("There is no product for the search")


def product_page(request, product_code):
    """
    Get a page for product
    :param request:
    :param product_code:
    :return: Page product
    """
    print(f"This will be the page for : {product_code}")
    product = product_code

    if product:
        product_array = logic.pull_product(product_code)
        print("Product is found in view ! (view)")

        if product_array is not None:
            [
                product_name,
                product_code,
                product_grade,
                product_image,
                categories,
                product_nutriments
            ] \
                = product_array

            context = {
                'categories': categories,
                'product_name': product_name,
                'product_code': product_code,
                'product_grade': product_grade,
                'product_image': product_image,
                'product_nutriments': product_nutriments,
            }
            return render(request, 'store/product.html', context)

        else:
            print("Product array can't be complete...")
            raise Http404("Product array can't be complete...")
    else:
        print("Product page can't be found...")
        raise Http404("Product page can't be found...")


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@transaction.atomic
def profile_page(request):
    """
    User page
    :param request:
    :return:
    """

    query_user = User.objects.filter(id=request.user.id)
    print(f" Query user : {query_user}")
    if query_user.exists():
        user = User.objects.get(id=request.user.id)
        Profile.objects.get_or_create(user=query_user[0])
        profile = Profile.objects.get(user=user)

        context = {
            'username': user.username,
            'profile': profile,
            'profile_user': profile.user,
            'user': user,
        }
        return render(request, 'store/profile.html', context)
    raise Http404("User page can't be found...")


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@transaction.atomic
def update_profile(request):
    """
    Update profile
    :param request:
    :return: Updated profile
    """

    profile_user = request.GET.get('profile_user')
    gender = request.GET.get('gender')
    email = request.GET.get('email')

    user_query = User.objects.filter(id=profile_user)
    user = User.objects.get(id=profile_user)
    profile = Profile.objects.get(user=user_query[0])

    profile.gender = gender
    profile.save()

    user.email = email
    user.save()
    return profile_page(request)


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@transaction.atomic
def products_page(request):
    """
    Page of products
    :param request:
    :return:
    """
    pairs = logic.create_user_list(request.user)

    if pairs is not None:
        paginator = Paginator(pairs, 6)

        page = request.GET.get('page')
        try:
            pairs = paginator.page(page)
        except PageNotAnInteger:
            pairs = paginator.page(1)
        except EmptyPage:
            pairs = paginator.page(paginator.num_pages)

        context = {
            'pairs': pairs,
            'paginate': True
        }
        return render(request, 'store/products.html', context)
    raise Http404("Products can't be found...")


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@transaction.atomic
def save_products_pair(request, product_code, substitute_code):
    """
    Stare a product
    :param request:
    :param product_code:
    :param substitute_code:
    :return: Page of products
    """

    if product_code and substitute_code:

        print(f"Saving {substitute_code} and {product_code} ")
        # Get both products
        product_array = logic.get_product_array(product_code)
        substitute_array = logic.search_product(substitute_code)

        product_is_saved = False
        if product_array is not None:
            print(f"product_array : {product_array}")
            product_is_saved = logic.save_product(product_array)

        substitute_is_saved = False
        if substitute_array is not None:
            print(f"substitute_array : {substitute_array}")
            substitute_is_saved = logic.save_product(substitute_array)

        stared = False
        if product_is_saved and substitute_is_saved:
            stared = logic.stare_product(request.user, product_array, substitute_array)

        if stared:
            context = {
                'substitute_code': substitute_code,
                'product_code': product_code
            }
            return render(request, 'store/save.html', context)

        else:
            raise Http404("Not able to save product and substitute")

    raise Http404("There is no product and substitute to save")


@login_required(login_url=settings.LOGIN_REDIRECT_URL)
@transaction.atomic
def delete_products_pair(request, product_id, substitute_id):
    """
    Stare a product
    :param request:
    :param product_id:
    :param substitute_id:
    :return: Page of products
    """
    delete = logic.delete_product(request.user, product_id, substitute_id)
    context = RequestContext(request)

    if delete is False:
        response = render_to_response('store/products.html', {"code": 404}, context)
        response.status_code = 404
    else:
        response = render_to_response('store/products.html', {"code": 200}, context)
        response.status_code = 200

    return products_page(request)

store/templates/store/base.html
<!DOCTYPE html>
<html lang="fr">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Pur Beurre">

    <title>Pur Beurre</title>

    {% load static %}

    <link rel="shortcut icon" type="image/png"
          href="{% static 'store/img/logo_pur_beurre.png' %}"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'store/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'store/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- Font animations -->
    <link rel="stylesheet" href="{% static 'store/css/font-animations.css' %}">

    <!-- Carrot font -->
    <link href="https://file.myfontastic.com/APp7oD6F8Dt6k6mpHFKhT6/icons.css" rel="stylesheet">

    <!-- Plugin CSS -->
    <link href="{% static 'store/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'store/css/creative.min.css' %}" rel="stylesheet">

    <!-- Custom style -->
    <link href="{% static 'store/css/style.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Navigation -->
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'index' %}#page-top">
            <span><img src="{% static 'store/img/navigation/icon.png' %}" alt="logo"></span>
            <span>Pur Beurre</span>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <form action="{% url 'store:search' %}" method="get" accept-charset="utf-8" class="navbar-form search" role="search">
                  <div class="input-group">
                    <input type="text" class="form-control text-center search" placeholder="Rechercher" name="query">
                    <div class="input-group-btn">
                        <button class="btn btn-warning" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                </form>
            </li>
              {% if user.is_authenticated %}
              <li class="nav-item menu">
              <a class="nav-link js-scroll-trigger" href="{% url 'store:profile_page'%}">
                  <i class="fas fa-user"></i>
                  <span>Mon compte</span>
              </a>
            </li>
               <li class="nav-item menu">
              <a class="nav-link js-scroll-trigger" href="{% url 'store:products' %}">
                  <i class="icon-noun-carrot-29691"></i>
                  <span>Mes produits</span>
              </a>
            </li>
              <li class="nav-item menu">
              <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}">
                  <i class="fas fa-sign-out-alt"></i>
                  <span>Déconnexion ({{user.username}}) </span>
              </a>
            </li>
              {% else %}
              <li class="nav-item menu">
              <a class="nav-link js-scroll-trigger" href="{% url 'login' %}">
                  <i class="fas fa-user"></i>
                  <span>Connexion</span>
              </a>
            </li>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
{% block body %}{% endblock %}
<section style="padding:10px !important;" class="bg-dark text-white">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <a href="{% url 'store:legal'%}">Mentions légales</a>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <a href="{% url 'index' %}#contact">Contact</a>
            </div>
          </div>
        </div>
      </div>
    </section>
<!-- Bootstrap core JavaScript -->
<script src="{% static 'store/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'store/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'store/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'store/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
<script src="{% static 'store/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'store/js/creative.min.js' %}"></script>

</body>

</html>

store/templates/store/results.html
{% extends 'store/base.html' %}

{% load static %}

{% block body %}
 {% for product in product_name %}
{% if forloop.first %}
<header class="masthead text-center text-white d-flex">
    <div id='product' class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>{{product_name|title|truncatewords:3}}</strong>
                </h1>
                <hr>
                </div>
                <div class="col-lg-8 mx-auto">
                    <div title="{{product_name|title}}" class="col-sm-4 mx-auto text-center">

                        {% if product_grade %}
                        <span class="product_grade score_{{product_grade}}">{{product_grade|upper}}</span>
                        {% endif %}
                        <a href="{% url 'store:product_page' product_code=product_code %}#product_page">
                            <img style="max-width:400px;max-height:120px;"
                                class='product_result img-responsive img-rounded js-scroll-trigger'
                                src="{{product_image}}" title='{{product_name}}' alt='{{product_name}}'></a></span>
                        <div class="mx-auto">
                            {% if full_result %}
                            <a class='btn btn-warning js-scroll-trigger'
                               href="{% url 'store:product_page' product_code=product_code %}#product_page">
                                Fiche produit
                            </a><br><br>
                            <a class='btn btn-warning' href="https://fr.openfoodfacts.org/produit/{{product_code}}/">
                                Fiche Open Food Fact
                            </a><br><br>
                            <a class='btn btn-warning js-scroll-trigger' href="#substitutes">▼</a>
                            {% else %}
                            <a href="{% url 'store:search' product_code=product_code %}#substitutes"
                                    style="color:black;text-decoration: none;">
                            <button data-toggle="modal"  class='btn btn-warning' data-target="#search">
                                      Voir les substituts
                            </button>
                            </a>
                            <!-- Modal -->
                            <div style='color:black;' class="modal fade" id='search' role="dialog">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Recherche ...</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>Nous recherchons les substituts pour {{ product_name }}</p>
                                        </div>
                                        <div class="modal-footer">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}

        </div>
    </div>
</header>
{% if full_result %}
<section class="bg-primary" id="substitutes">
    <div class="container">
        <div class="text-center text-faded ">
            {% if substitutes %}
                {% for substitute in substitutes %}
                {% if forloop.first %}
                {% if product_grade == substitute.2 %}
                <h2 class="section-heading text-white">Dans la même catégorie</h2>
                <p><small>A défaut de pouvoir vous proposer de meilleurs produits en voilà de même grade</small></p>
                {% else %}
                <h2 class="section-heading text-white">Les substituts</h2>
                {% endif %}
                {% endif %}
                    {% if forloop.first %}
                    <div class="row">
                        {% endif %}
                            <div class="col-xs-4 col-lg-4">
                                <ul>
                                    <li style="list-style:none;">
                                        <p>{{substitute.0|title|truncatewords:3}}</p>
                                        {% if substitute.2 == "a" %}
                                        <p class="substitute_grade score_a">{{substitute.2|upper}}</p>
                                        {% elif substitute.2 == "b" %}
                                        <p class="substitute_grade score_b">{{substitute.2|upper}}</p>
                                        {% elif substitute.2 == "c" %}
                                        <p class="substitute_grade score_c">{{substitute.2|upper}}</p>
                                        {% elif substitute.2 == "d" %}
                                        <p class="substitute_grade score_d">{{substitute.2|upper}}</p>
                                        {% else %}
                                        <p class="substitute_grade score_e">{{substitute.2|upper}}</p>
                                        {% endif %}
                                        <a href="{% url 'store:product_page' product_code=substitute.1 %}">
                                            <img style="max-width:400px;max-height:120px;" title="{{substitute.0}} (Grade : {{substitute.2}})"
                                             class='product_result img-responsive img-rounded'
                                                 src={{substitute.3}} alt='{{substitute.0}}'></a>
                                        <br>
                                        <button data-toggle="modal"  data-target=".save{{forloop.counter}}">
                                            Enregistrer
                                        </button>
                                        <!-- Modal -->
                                        <div style='color:black;' class="modal fade save{{forloop.counter}}" role="dialog">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title">Enregistrer</h4>
                                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Valider l'enregistrement du produit {{ substitute.0 }} en cliquant sur
                                                            enregistrer ou fermer cette fenêtre.</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <a href="{% url 'store:save' product_code=product_code substitute_code=substitute.1 %}">
                                                            <button type="button" class="btn btn-default">Enregistrer</button>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <br><br>
                                        <!--<p>{{substitute.categories}}</p>-->
                                        <!--{{substitute.nutriments}}-->
                                        <!--{{substitute.code}}-->
                                    </li>
                                </ul>
                            </div>
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                    {% if forloop.last %}</div>{% endif %}
                {% endfor %}
                 <a class='btn btn-warning js-scroll-trigger' href="#product">Revenir en haut</a>
            {% else %}
            <div class="text-center text-faded ">
            <hr class="light my-4">
            <p>Il n'y a pas de meilleurs produits que celui ci dans sa catégorie !</p>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% else %}
<section class="bg-primary">
    <div class="container text-faded">
        <p class="text-center">
            <small>
            Cette application utilise la base de données Openfoodfacts et le framework Django !
            <br>
            ( https://openfoodfacts.org )
            </small>
        </p>
    </div>
</section>
{% endif %}
{% endblock %}

store/templates/store/save.html
{% extends 'store/base.html' %}

{% load static %}

{% block body %}
<header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Produit enregistré !</strong>
                </h1>
                <hr>
                <form method="get"
                      action="{% url 'store:products' %}"
                      accept-charset="utf-8">
                    <button class='btn btn-warning' type="submit">
                        Consulter mes produits
                    </button>
                </form>
                <br>
                <br>
                <form method="get"
                      action="{% url 'store:search' product_code=product_code %}"
                      accept-charset="utf-8">
                    <button class='btn btn-warning' type="submit">
                        Revenir à mon résultat
                    </button>
                </form>
            </div>
            <div class="col-lg-8 mx-auto">
                <div title="" class="col-sm-4 mx-auto text-center"></div>
            </div>
        </div>
    </div>
</header>
<section class="bg-primary">
    <div class="container text-faded">
        <p class="text-center">
            <small>
            Cette application utilise la base de données Openfoodfacts et le framework Django !
            <br>
            ( https://openfoodfacts.org )
            </small>
        </p>
    </div>
</section>
{% endblock %}

store/templates/store/signup.html
{% extends 'store/base.html' %}

{% load static %}

{% block body %}
<header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Inscription</strong>
                </h1>
                <hr>
            </div>
            <div class="col-lg-8 mx-auto">
                <h2 class="text-faded mb-5">
                    Retrouvez vos informations personnelles,<br>
                    enregistrez de nouvelles alternatives !</h2>
            </div>
        </div>
    </div>
</header>

<section class="bg-primary" id="connection">
    <div class="container">
        <div class="row">
            <div class="mx-auto text-center text-faded ">
                <h2 class="section-heading text-white">Entrez vos informations personnelles</h2>
                <hr class="light my-4">
                <p class="text-faded mb-4">
                    Merci de nous faire confiance, <br>
                    dans le doute n'utilisez pas forcément des mots de passe identiques pour tous les sites...<br>
                    <small>Héhéhé on dit ça mais en principe vous devriez toujours suivre ce conseil !</small>
                </p>
                <form class="form-horizontal" method="post">{% csrf_token %}
                <fieldset>
                    <legend>{{ title }}</legend>
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="control-group error">
                                <label class="control-label">{{ field.label }}</label>
                                <div class="controls">{{ field }}
                                    <span class="help-inline">
                                        {% for error in  field.errors %}<br>{{ error }}<br>{% endfor %}
                                    </span>
                                </div>
                            </div>
                        {% else %}
                            <div class="control-group">
                                <label class="control-label">{{ field.label }}</label>
                                <div class="controls">{{ field }}
                                    {% if field.help_text %}
                                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                        <br>
                    {% endfor %}
                </fieldset>
                <div class="form-actions">
                    <button type="submit" class="btn btn-warning" >S'inscrire</button>
                </div>
            </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}